@startuml

class MassRequirement <<requirement>> {
  text = "The actual mass shall be less than the required mass"
}
class ReliabilityRequirement <<requirement>> {
  text = "The actual reliability shall be greater than the required reliability"
}
class TorqueGenerationRequirement <<requirement>> {
  text = "The engine shall generate torque as a function of RPM as shown in Table 1."
}
class DrivePowerOutputRequirement <<requirement>> {
  text = "The engine shall provide a connection point to transfer torque to the transmission."
}
class FuelEconomyRequirement <<requirement>> {
  text = "The vehicle shall maintain an average fuel economomy of at least x miles per gallon for the nominal 
                driving scenario"
}

class vehicleSpecification <<requirement>> {
  text = "The total mass of the vehicle shall be less than or equal to the required mass.
                        Assume total mass includes a full tank of gas of 60 kg"
}
class vehicleMassRequirement <<requirement>> {
  text = "The total mass of the vehicle shall be less than or equal to the required mass.
                        Assume total mass includes a full tank of gas of 60 kg"
}
class vehicleFuelEconomyRequirements <<requirement>> {
  text = "fuel economy requirements group"
}
class cityFuelEconomyRequirement <<requirement>> {
}
class highwayFuelEconomyRequirement <<requirement>> {
}
class engineSpecification <<requirement>> {
  text = "The total mass of the engine shall be less than or equal to the required mass."
}
class engineMassRequirement <<requirement>> {
  text = "The total mass of the engine shall be less than or equal to the required mass."
}
class torqueGenerationRequirement <<requirement>> {
}
class drivePowerOutputRequirement <<requirement>> {
}
class transportRequirements <<requirement>> {
  text = "deliver passenger to destination safely, comfortably, and within acceptable time"
}

vehicleMassRequirement --|> MassRequirement
cityFuelEconomyRequirement --|> FuelEconomyRequirement
highwayFuelEconomyRequirement --|> FuelEconomyRequirement
engineMassRequirement --|> MassRequirement
torqueGenerationRequirement --|> TorqueGenerationRequirement
drivePowerOutputRequirement --|> DrivePowerOutputRequirement

vehicleSpecification *-- vehicleMassRequirement
vehicleSpecification *-- vehicleFuelEconomyRequirements
vehicleSpecification *-- cityFuelEconomyRequirement
vehicleSpecification *-- highwayFuelEconomyRequirement
engineSpecification *-- engineMassRequirement
engineSpecification *-- torqueGenerationRequirement
engineSpecification *-- drivePowerOutputRequirement

vehicle_b.engine ..> engineSpecification : <<satisfy>>
vehicle_b ..> vehicleSpecification : <<satisfy>>

@enduml
