@startuml

component "Vehicle" as Vehicle {
  component "engine : Engine" as engine
  component "transmission : Transmission" as transmission
  component "wheel : Wheel" as wheel
  component "chassis : Chassis" as chassis
}

engine -- transmission : engineToTrans

@enduml
